### ISSUE TITLE
Register SeisBase? 

### ISSUE THREAD

**Issue by tclements** [JuliaSeismo/SeisBase.jl#8]
@stepholinger just submitted an awesome PR (https://github.com/tclements/SeisNoise.jl/pull/113) to move SeisNoise.jl to using SeisBase. I'd like to have SeisBase registered as an official Julia package before making it a SeisNoise dependency - see install issue here https://github.com/tclements/SeisNoise.jl/pull/113#issuecomment-1800912825. 

SeisBase is passing all tests - is it ready to register? https://github.com/JuliaRegistries/General/blob/master/README.md

**Comment by niyiyu** [comment]
I am trying to register the package here: https://github.com/JuliaRegistries/General/pull/95336. Waiting for manual approval and after that, we should be good to go.

**Comment by juliohm** [comment]
Thanks for contributing a seismic package! Can you please provide a comparison with the SeismicJulia packages? https://github.com/SeismicJulia

**Comment by mdenolle** [comment]
Our julia organization comes from different groups, and historically, the SeismicJulia organization has made efforts toward reading a specific data format (SEGY) and processing data in a style of applied geophysical research.
SeisBase is a copy of [SeisIO](https://github.com/jpjones76/SeisIO.jl/) (already registered) that aimed to have a broader, more generic, I/O readers for a vast range of data formats. In order to migrate other Julia packages (e.g., [SeisNoise](https://github.com/tclements/SeisNoise.jl)) into a community-maintained package (e,g., a future https://github.com/JuliaSeismo/SeisNoise.jl), we had to update SeisIO with new HDF5 dependencies. The code owner of SeisIO refused to continue accepting contributions and PR without salary, so we had to recreate a version that would be community-maintained.

**Comment by juliohm** [comment]
Thank you @mdenolle for sharing the motivations. I am not following the seismic packages closely, but I am happy to know that this is a community-driven effort 💯

Perhaps someone could add a note to the README of JuliaSeismo mentioning these historical details? It would certainly help future potential contributors.

**Comment by mdenolle** [comment]
great @juliohm ! Just added [here](https://github.com/JuliaSeismo/.github/blob/main/profile/README.md).

**Comment by niyiyu** [comment]
Just merged in the general registry! Thanks everyone!
